import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { AuthProvider } from "@/hooks/AuthContext";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import styles from "@/styles/page.module.css";
import { HeaderProvider } from "@/hooks/HeaderContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//className={`${geistSans.variable} ${geistMono.variable}`}

export const metadata: Metadata = {
  title: "Quiz Dash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <HeaderProvider>
        <html lang="ja">
          <body>
            <Header />
            <main className={styles.page}>{children}</main>
            <Footer />
          </body>
        </html>
      </HeaderProvider>
    </AuthProvider>
  );
}
